health: # Healing configuration, all values in %
  healingPotionAt: 80
  manaPotionAt: 60
  rejuvPotionAtLife: 40
  rejuvPotionAtMana: 40
  mercHealingPotionAt: 60
  mercRejuvPotionAt: 20

bindings: # Hotkey configuration for potions
  # You can provide a single number or a list. Example: potionHP: [1, 2]
  potionHP: [1,2]
  potionMANA: [3,4]
  #potionREJUV: 2

timings: # Delay time beetween actions (seconds)
  rejuvInterval: 1
  healingInterval: 4
  manaInterval: 5
  healingMercInterval: 6
